# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

# edit here triggers, cf. https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml
trigger:
- master
pr:
  autoCancel: true
  branches:
    include:
    - master

pool:
  vmImage: 'ubuntu-18.04'
jobs:
  - job: 'tuplex'
    timeoutInMinutes: 180
    steps:
      - script: sudo bash scripts/ubuntu1804/install_mongodb.sh
        displayName: 'Install MongoDB'
      - script: cd tuplex/python && python3 mongodb_test.py && pkill mongod
        displayName: 'Test MongoDB init'
      - script: sudo bash scripts/install_azure_ci_reqs.sh
        displayName: 'Install required packages'
      - script: sudo apt-get install -y python3-setuptools ninja-build && sudo apt-get remove -y python-pexpect python3-pexpect && sudo python3.7 -m pip install --upgrade pip && sudo python3.7 -m pip uninstall -y pygments && sudo python3.7 -m pip install pytest pygments>=2.4.1 MarkupSafe==2.0 pexpect setuptools astor PyYAML jupyter nbformat pymongo eventlet==0.30.0 gunicorn pymongo && jupyter --version
        displayName: 'Install python dependencies'
      - script: TUPLEX_BUILD_ALL=1 CMAKE_ARGS="-DBUILD_WITH_ORC=ON -DLLVM_ROOT_DIR=/usr/lib/llvm-9 -DCMAKE_BUILD_TYPE=Release -DBUILD_FOR_CI=ON" python3 setup.py install --user
        displayName: 'Build Tuplex'
      - script: cd build/temp.linux-x86_64-3.7 && ctest --timeout 180 --output-on-failure
        displayName: 'C++ tests'
      - script: cd build/temp.linux-x86_64-3.7/dist/python && python3.7 -m pytest -x --full-trace -l --log-cli-level=DEBUG --capture=tee-sys
        displayName: 'Python tests'
